name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'v[0-9]*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'v[0-9]*'

env:
  # FIXME: Use docker/dockerfile when moved to docker org
  REPO_SLUG: "crazymax/dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        channel:
          - mainline
          - labs
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Install semver npm pkg
        run: npm install semver
      -
        name: Check semver type
        id: semver
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            const semver = require('semver')
            if (!/^refs\/tags\//.test(context.ref)) {
              return 'invalid'
            }
            vraw = context.ref.replace(/^refs\/tags\//g, '').replace(/\//g, '-')
            if (!semver.valid(vraw)) {
              return 'invalid'
            }
            if (semver.prerelease(vraw)) {
              return 'prerelease'
            }
            return 'release'
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REPO_SLUG }}
          ### dockerfile frontend versioning
          ### on semver tag:
          # docker/dockerfile:1.0.1
          # docker/dockerfile:1.1
          # docker/dockerfile:1
          # docker/dockerfile:latest
          # docker/dockerfile:1.0.1-labs
          # docker/dockerfile:1.1-labs
          # docker/dockerfile:1-labs
          # docker/dockerfile:latest-labs
          ### on pre-release tag:
          # docker/dockerfile:1.1.0-rc.1
          # docker/dockerfile:1.1.0-rc.1-labs
          ### on push default branch (master):
          # docker/dockerfile:master
          # docker/dockerfile:master-labs
          tags: |
            type=semver,pattern={{version}},enable=${{ matrix.channel == 'mainline' }}
            type=semver,pattern={{version}},suffix=-${{ matrix.channel }},enable=${{ matrix.channel != 'mainline' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ matrix.channel == 'mainline' }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.channel }},enable=${{ matrix.channel != 'mainline' }}
            type=semver,pattern={{major}},enable=${{ matrix.channel == 'mainline' }}
            type=semver,pattern={{major}},suffix=-${{ matrix.channel }},enable=${{ matrix.channel != 'mainline' }}
            type=ref,event=branch,enable=${{ matrix.channel == 'mainline' }}
            type=ref,event=branch,suffix=-${{ matrix.channel }},enable=${{ matrix.channel != 'mainline' }}
            type=raw,value=latest,enable=${{ steps.semver.outputs.result == 'release' && matrix.channel == 'mainline' }}
            type=raw,value=latest,suffix=-${{ matrix.channel }},enable=${{ steps.semver.outputs.result == 'release' && matrix.channel != 'mainline' }}
            type=ref,event=pr
          bake-target: meta-helper
          flavor: |
            latest=false
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image
        uses: docker/bake-action@v1
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: image-cross
          push: ${{ github.event_name != 'pull_request' }}
        env:
          CHANNEL: ${{ matrix.channel }}
