name: validate

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'v[0-9]*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'v[0-9]*'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - lint
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run
        uses: docker/bake-action@v1
        with:
          targets: ${{ matrix.target }}
